
document.write("<footer id=\"footer\">");
document.write("	<div id=\"usptoAppFooter\">");
document.write("		<div class=\"container-fluid\">");
document.write("			<div class=\"row\">");
document.write("				<div class=\"uspto-footer-top col-sm-12\">");
document.write("					<div class=\"uspto-footer-logo col-sm-10\"> <a class=\"logo\" href=\"http:\/\/www.uspto.gov\/\" title=\"United States Patent and Trademark Office - An Agency of the Department of Commerce\"> <span class=\"sr-only\">United States Patent and Trademark Office - An Agency of the Department of Commerce<\/span> <\/a> <\/div>");
document.write("					<div class=\"uspto-footer-watermark col-sm-2\" title=\"United States Patent and Trademark Office - An Agency of the Department of Commerce\"> <span class=\"sr-only\">United States Patent and Trademark Office - An Agency of the Department of Commerce<\/span> <\/div>");
document.write("				<\/div>");
document.write("				<div class=\"uspto-footer-middle col-sm-12\">");
document.write("					<div class=\"navbar-header\">");
document.write("						<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-topic\"> Browse By Topic <i class=\"icon icon-sort-desc icon-inverse\"><\/i> <\/button>");
document.write("					<\/div>");
document.write("					<div class=\"uspto-footer-column col-sm-3 collapse navbar-collapse\" id=\"navbar-collapse-topic\">");
document.write("						<h2>Browse By Topic<\/h2>");
document.write("						<ul>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/patent\">Patents<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/trademark\">Trademarks<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/learning-resources\">Learning &amp; Resources<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/about-us\">About the USPTO<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/learning-and-resources\/glossary\">Glossary<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/careers\">Careers<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/about-us\/contact-us\">Contact Us<\/a><\/li>");
document.write("						<\/ul>");
document.write("					<\/div>");
document.write("					<div class=\"navbar-header\">");
document.write("						<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-about\"> About This Site <i class=\"icon icon-sort-desc icon-inverse\"><\/i> <\/button>");
document.write("					<\/div>");
document.write("					<div class=\"uspto-footer-column col-sm-3 collapse navbar-collapse\" id=\"navbar-collapse-about\">");
document.write("						<h2>About This Site<\/h2>");
document.write("						<ul>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/using-usptogov\/accessibility-uspto-website\">Accessibility<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/privacy-policy\">Privacy Policy<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/terms-use-uspto-website\">Terms of Use<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/about-us\/security\">Security<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/blog\/ebiz\/\">Systems Status<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/sitemap\">Site Map<\/a><\/li>");
document.write("						<\/ul>");
document.write("					<\/div>");
document.write("					<div class=\"navbar-header\">");
document.write("						<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-uspto\"> USPTO Background <i class=\"icon icon-sort-desc icon-inverse\"><\/i> <\/button>");
document.write("					<\/div>");
document.write("					<div class=\"uspto-footer-column col-sm-3 collapse navbar-collapse\" id=\"navbar-collapse-uspto\">");
document.write("						<h2>USPTO Background<\/h2>");
document.write("						<ul>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/about-us\/performance-and-planning\/federal-activities-inventory-reform-fair-act\">Federal Activity Inventory Reform Act (FAIR)<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/about-us\/performance-and-planning\">USPTO Budget and Performance<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/learning-and-resources\/ip-policy\/electronic-freedom-information-act-e-foia\">Freedom of Information Act<\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/learning-and-resources\/information-quality-guidelines\">Information Quality Guidelines<\/a><\/li>");
document.write("						<\/ul>");
document.write("					<\/div>");
document.write("					<div class=\"navbar-header\">");
document.write("						<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-federal\"> Federal Government <i class=\"icon icon-sort-desc icon-inverse\"><\/i> <\/button>");
document.write("					<\/div>");
document.write("					<div class=\"uspto-footer-column col-sm-3 collapse navbar-collapse\" id=\"navbar-collapse-federal\">");
document.write("						<h2>Federal Government<\/h2>");
document.write("						<ul>");
document.write("							<li><a href=\"http:\/\/www.regulations.gov\" target=\"_blank\">Regulations.gov<span class=\"ext\"> <span class=\"icon icon-external-link icon-inverse\"><span class=\"sr-only\"> (link is external)<\span><\span><\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.stopfakes.gov\" target=\"_blank\">StopFakes.gov<span class=\"ext\"> <span class=\"icon icon-external-link icon-inverse\"><span class=\"sr-only\"> (link is external)<\span><\span><\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.usa.gov\" target=\"_blank\">USA.gov<span class=\"ext\"> <span class=\"icon icon-external-link icon-inverse\"><span class=\"sr-only\"> (link is external)<\span><\span><\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.commerce.gov\" target=\"_blank\">Department of Commerce<span class=\"ext\"> <span class=\"icon icon-external-link icon-inverse\"><span class=\"sr-only\"> (link is external)<\span><\span><\/a><\/li>");
document.write("							<li><a href=\"http:\/\/www.uspto.gov\/learning-and-resources\/ip-policy\/enforcement\/strategy-targeting-organized-piracy-stop\">Strategy Targeting Organized Piracy<\/a><\/li>");
document.write("						<\/ul>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/footer>");
document.write("");
